### ISSUE TITLE
Public release checklist

### ISSUE THREAD

**Issue by scaytrase** [bankiru/rpc-server-bundle#1]
- [x] Travis
- [x] Insight
- [x] https://scrutinizer-ci.com/
- [ ] https://coveralls.io/
- [x] Badges for all above and packagist

**Comment by scaytrase** [comment]
Coveralls dropped in favor of scrutinizer coverage badge
